name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Installing Requirements #Installing make >> https://theos.dev/docs/parallel-building <<
        run: |
            printf "\033[33m==>\033[0m Installing Homebrew\n" && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" > /dev/null 2>&1 && printf "\033[32m==>\033[0m Homebrew successfully installed\n" || printf "\033[31m==>\033[0m Oops! something goes wrong. (check logs for details)\n"
            printf "\033[33m==>\033[0m Installing make\n" && brew install make && echo PATH=\"$(brew --prefix make)/libexec/gnubin:\$PATH\" >> .env && printf "\033[32m==>\033[0m make successfully installed\n" || printf "\033[31m==>\033[0m Oops! something goes wrong. (check logs for details)"
            printf "\033[33m==>\033[0m Installing dpkg\n" && brew install dpkg && printf "\033[32m==>\033[0m dpkg successfully installed\n" || printf "\033[31m==>\033[0m Oops! something goes wrong. (check logs for details)"
            printf "\033[33m==>\033[0m Installing ldid\n" && brew install ldid && printf "\033[32m==>\033[0m ldid successfully installed\n" || printf "\033[31m==>\033[0m Oops! something goes wrong. (check logs for details)"
            echo "export THEOS=${{ github.workspace }}/theos" >> .env
      - name: Installing Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      - name: Installing iOS 14.1 SDK # Download SDK (SDK Credits: Randy420)
        run: |
          cd ${{ github.workspace }}/theos/sdks
          printf "\033[33m==> \033[0m Installing SDK\n" && wget https://www.dropbox.com/s/jvonok3de24ibsz/14.1.zip > /dev/null 2>&1 && unzip 14.1.zip > /dev/null 2>&1 && printf "\033[32m==> \033[0m SDK successfully installed\n" || printf "\033[31m==> \033[0m Oops! something goes wrong. (check logs for details)"
      - name: Build Tweak
        run: |
          source .env
          make package
          mv -v packages/*.deb cellularx.deb

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: Tweak
          path: |
            /Users/runner/work/CellularX/CellularX/packages/cellularx.deb
