name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Installing Requirements #Installing make >> https://theos.dev/docs/parallel-building <<
        run: |
            printf "\033[33m==>\033[0m Installing Homebrew\n" && /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" > /dev/null 2>&1 && printf "\033[32m==>\033[0m Homebrew successfully installed\n" || printf "\033[31m==>\033[0m Oops! something goes wrong. (check logs for details)\n"
            printf "\033[33m==>\033[0m Installing make\n" && brew install make && echo PATH=\"$(brew --prefix make)/libexec/gnubin:\$PATH\" >> .env && printf "\033[32m==>\033[0m make successfully installed\n" || printf "\033[31m==>\033[0m Oops! something goes wrong. (check logs for details)"
            printf "\033[33m==>\033[0m Installing dpkg\n" && brew install dpkg && printf "\033[32m==>\033[0m dpkg successfully installed\n" || printf "\033[31m==>\033[0m Oops! something goes wrong. (check logs for details)"
            printf "\033[33m==>\033[0m Installing ldid\n" && brew install ldid && printf "\033[32m==>\033[0m ldid successfully installed\n" || printf "\033[31m==>\033[0m Oops! something goes wrong. (check logs for details)"
            echo "export THEOS=${{ github.workspace }}/theos" >> .env
      - name: Installing Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          path: theos
          submodules: recursive
      - name: Installing iOS 14.1 SDK # Download SDK (SDK Credits: Randy420)
        run: |
          cd ${{ github.workspace }}/theos/sdks
          printf "\033[33m==> \033[0m Installing SDK\n" && wget https://www.dropbox.com/s/jvonok3de24ibsz/14.1.zip > /dev/null 2>&1 && unzip 14.1.zip > /dev/null 2>&1 && printf "\033[32m==> \033[0m SDK successfully installed\n" || printf "\033[31m==> \033[0m Oops! something goes wrong. (check logs for details)"
      - name: Build Alerts
        run: |
          source .env
          cd Stock/
          make clean package
          mv -v packages/*.deb FavourAlert-Stock.deb
          dpkg -x FavourAlert-Stock.deb $(PWD)
          mv -v Library/MobileSubstrate/DynamicLibraries/AppleFavour_StockAlert.dylib $(PWD)
          cd ../SCL/
          make clean package
          mv -v packages/*.deb SCL-Alert.deb
          dpkg -x SCL-Alert.deb $(PWD)
          mv -v Library/MobileSubstrate/DynamicLibraries/applefavour.dylib $(PWD)
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: AlertBanners.zip
          path: |
            /Users/runner/work/AlertBanners/AlertBanners/Stock/FavourAlert-Stock.deb
            /Users/runner/work/AlertBanners/AlertBanners/Stock/AppleFavour_StockAlert.dylib
            /Users/runner/work/AlertBanners/AlertBanners/SCL/SCL-Alert.deb
            /Users/runner/work/AlertBanners/AlertBanners/SCL/applefavour.dylib
